### ISSUE TITLE
How to setup the demo in Godot 3

### ISSUE THREAD

**Issue by hiulit** [securas/raindemo#2]
Hi there!

I would really love to use, or at least take a look at the code, this effect and apply it on something I'm working on but I can't figure out how to use it.

I downloaded your project as a zip file and the first thing I noticed is that it's missing a `project.godot` file. Anyway, I tried to run the `raindemo.tscn` and it doesn't do anything, hehe! :P

What am I missing here? Should I try to run another scene?

Thanks!

**Comment by securas** [comment]
This project was made in Godot 2.1

**Comment by hiulit** [comment]
Ohh... I see, haha! My bad!

Anyway, I saw that you use rain in Daisy Dangerous, so I took it from there and it's working.
One thing I'd like to ask you, if you don't mind, is: How can I make the rain appear in the whole screen/camera?

Thanks!
